# -*- coding: utf-8 -*-
"""healthcare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sn1l56a36WSbOpssWvJfn9n_bXWPWYQ1
"""

import pandas as pd
df = pd.read_csv('mtsamples.csv',engine="python",encoding="utf-8",on_bad_lines="skip")

df = df.drop('Unnamed: 0',axis=1)

df.head()

df.isnull().sum()

df.shape

# Since sample_name is the title of the report so it is pretty useless
df = df.drop('sample_name',axis=1)

# Since transcription is the main input so where transaction is NaN drop that rows
df = df[~(df['transcription'].isnull())]

df.head()

import matplotlib.pyplot as plt
df['transcription'].astype(str).apply(len).hist(bins=50, figsize=(10,4))

df['transcription'].astype(str).apply(len).describe()

df[df['transcription'].astype(str).apply(len)>10000]

# Dropped whose length is more than 10000
df = df[~(df['transcription'].astype(str).apply(len)>10000)]

df['transcription'].astype(str).apply(len).hist(bins=50, figsize=(10,4))

df['text_length'] = df['transcription'].astype(str).apply(len)

df.head()

import pandas as pd
import torch
from transformers import BartForConditionalGeneration, AutoTokenizer

model_name = "sshleifer/distilbart-cnn-12-6"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)
model = model.to("cuda" if torch.cuda.is_available() else "cpu")

print("Model loaded on:", "GPU" if torch.cuda.is_available() else "CPU")

def chunk_text(text, max_tokens=900, overlap=50):
    tokens = tokenizer.encode(text, truncation=False)
    chunks = []
    start = 0
    while start < len(tokens):
        end = min(start + max_tokens, len(tokens))
        chunk = tokenizer.decode(tokens[start:end], skip_special_tokens=True)
        chunks.append(chunk)
        start += max_tokens - overlap
    return chunks

def summarize_text(text, min_len=60, max_len=180):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=1024,
        truncation=True
    ).to(model.device)

    summary_ids = model.generate(
        inputs["input_ids"],
        max_length=max_len,
        min_length=min_len,
        length_penalty=2.0,
        num_beams=4,
        early_stopping=True
    )
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

def summarize_long_text(text, min_len=60, max_len=180):
    tokens = tokenizer.encode(text, truncation=False)

    if len(tokens) <= 1024:
        return summarize_text(text, min_len, max_len)

    # Chunk → summarize each → final pass
    chunks = chunk_text(text)
    chunk_summaries = [summarize_text(chunk, 40, 120) for chunk in chunks]
    combined = " ".join(chunk_summaries)
    return summarize_text(combined, min_len, max_len)

df = df.reset_index(drop=True)

import os
from tqdm import tqdm

checkpoint_file = 'mtsamples_checkpoint.csv'
BATCH_SIZE = 8

# Combine description + transcription
df['combined_text'] = (
    df['description'].fillna('') + ' ' + df['transcription'].fillna('')
).str.strip()

# Resume from checkpoint if exists
if os.path.exists(checkpoint_file):
    df_done = pd.read_csv(checkpoint_file)
    start_idx = df_done['patient_summary'].notna().sum()
    df['patient_summary'] = df_done['patient_summary']
    print(f"Resuming from row {start_idx}")
else:
    df['patient_summary'] = None
    start_idx = 0

for i in tqdm(range(start_idx, len(df))):
    df.at[i, 'patient_summary'] = summarize_long_text(df.at[i, 'combined_text'])
    if i % 100 == 0:
        df.to_csv(checkpoint_file, index=False)

df.to_csv('mtsamples_with_summary.csv', index=False)

df.head()

from rouge_score import rouge_scorer
import pandas as pd
import numpy as np

df = pd.read_csv('mtsamples_with_summary.csv')
df = df.dropna(subset=['patient_summary', 'description'])

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

scores = {'rouge1': [], 'rouge2': [], 'rougeL': []}

for _, row in df.iterrows():
    score = scorer.score(
        str(row['description']),      # reference
        str(row['patient_summary'])   # generated
    )
    scores['rouge1'].append(score['rouge1'].fmeasure)
    scores['rouge2'].append(score['rouge2'].fmeasure)
    scores['rougeL'].append(score['rougeL'].fmeasure)

print("=== ROUGE Scores ===")
print(f"ROUGE-1 : {np.mean(scores['rouge1']):.4f}")
print(f"ROUGE-2 : {np.mean(scores['rouge2']):.4f}")
print(f"ROUGE-L : {np.mean(scores['rougeL']):.4f}")

import pandas as pd
df = pd.read_csv('mtsamples_with_summary.csv')

df.head()

!pip install keybert sentence-transformers -q

import pandas as pd

df = pd.read_csv('mtsamples_with_summary.csv')
df = df.dropna(subset=['patient_summary'])
print(f"Rows available: {df.shape[0]}")
df[['patient_summary', 'keywords']].head(3)

from keybert import KeyBERT
from sentence_transformers import SentenceTransformer

# Medical domain BioBERT embedding model
embedding_model = SentenceTransformer("pritamdeka/BioBERT-mnli-snli-scinli-scitail-mednli-stsb")
kw_model = KeyBERT(model=embedding_model)

print("KeyBERT model loaded ✅")

def extract_keywords(text, top_n=10):
    if not text or len(str(text).strip()) == 0:
        return ""

    keywords = kw_model.extract_keywords(
        str(text),
        keyphrase_ngram_range=(1, 2),
        stop_words='english',
        top_n=top_n,
        use_mmr=True,       # Maximal Marginal Relevance for diversity
        diversity=0.5       # avoid redundant keywords
    )

    return ", ".join([kw[0] for kw in keywords])

from tqdm import tqdm
import os

checkpoint_file = 'mtsamples_with_keywords.csv'

# Resume from checkpoint if exists
if os.path.exists(checkpoint_file):
    df_done = pd.read_csv(checkpoint_file)
    df['extracted_keywords'] = df_done['extracted_keywords']
    start_idx = df['extracted_keywords'].notna().sum()
    print(f"Resuming from row {start_idx}")
else:
    df['extracted_keywords'] = None
    start_idx = 0

for i in tqdm(range(start_idx, len(df))):
    df.at[i, 'extracted_keywords'] = extract_keywords(df.at[i, 'patient_summary'])

    if i % 100 == 0:
        df.to_csv(checkpoint_file, index=False)

df.to_csv('mtsamples_with_keywords.csv', index=False)
print("All done ✅")

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

eval_model = SentenceTransformer("all-MiniLM-L6-v2")

eval_df = df.dropna(subset=['extracted_keywords', 'keywords'])

def keyword_similarity(kw1, kw2):
    if not kw1 or not kw2:
        return 0.0
    emb1 = eval_model.encode([str(kw1)])
    emb2 = eval_model.encode([str(kw2)])
    return cosine_similarity(emb1, emb2)[0][0]

scores = []
for _, row in tqdm(eval_df.iterrows(), total=len(eval_df)):
    score = keyword_similarity(row['extracted_keywords'], row['keywords'])
    scores.append(score)

print("=== Keyword Extraction Evaluation ===")
print(f"Mean Cosine Similarity : {np.mean(scores):.4f}")
print(f"Median                 : {np.median(scores):.4f}")
print(f"Min                    : {np.min(scores):.4f}")
print(f"Max                    : {np.max(scores):.4f}")

df.to_csv('mtsamples_with_keywords.csv', index=False)
df.head(3)

!pip install negspacy spacy -q
!python -m spacy download en_core_web_sm -q

import pandas as pd
import numpy as np

df = pd.read_csv('mtsamples_with_keywords.csv')

high_risk_terms = [
    'cancer', 'tumor', 'malignant', 'carcinoma', 'metastasis',
    'hemorrhage', 'bleeding', 'intracranial', 'hematoma',
    'sepsis', 'septic', 'shock', 'cardiogenic shock',
    'failure', 'heart failure', 'renal failure', 'liver failure',
    'respiratory failure', 'multi organ failure',
    'acute', 'critical', 'life threatening',
    'stroke', 'cva', 'infarction', 'myocardial infarction',
    'embolism', 'pulmonary embolism', 'thrombosis',
    'aneurysm', 'rupture', 'dissection',
    'necrosis', 'gangrene',
    'seizure', 'status epilepticus',
    'unconscious', 'coma', 'unresponsive',
    'fatal', 'death', 'terminal',
    'emergency', 'urgent',
    'massive', 'severe', 'aggressive',
    'cardiac arrest', 'ventricular fibrillation',
    'ventricular tachycardia',
    'hypoxia', 'hypoxemia',
    'intubation', 'ventilator',
    'transplant', 'metastatic',
    'brain tumor', 'glioblastoma',
    'acute kidney injury',
    'acute coronary syndrome',
    'unstable angina',
    'respiratory distress',
    'acute respiratory distress syndrome',
    'ards',
    'meningitis',
    'encephalitis',
    'perforation',
    'obstruction',
    'collapse'
]

medium_risk_terms = [
    'infection', 'inflammation',
    'chronic', 'persistent', 'recurrent',
    'hypertension', 'high blood pressure',
    'diabetes', 'diabetic',
    'fracture', 'injury', 'trauma',
    'disorder', 'syndrome',
    'abnormal', 'abnormality',
    'deficiency', 'insufficiency',
    'dysfunction', 'impaired',
    'pain', 'chest pain', 'back pain',
    'disease', 'lesion', 'mass',
    'elevated', 'reduced',
    'progressive', 'moderate',
    'anemia', 'obesity',
    'arthritis', 'osteoarthritis',
    'asthma', 'copd',
    'bronchitis', 'pneumonia',
    'fibrosis',
    'arrhythmia',
    'tachycardia', 'bradycardia',
    'ischemia',
    'edema',
    'ulcer',
    'infection',
    'kidney disease',
    'liver disease',
    'thyroid disorder',
    'depression',
    'anxiety',
    'migraine',
    'neuropathy',
    'hyperlipidemia',
    'dementia',
    'parkinson',
    'osteoporosis',
    'scoliosis',
    'hernia',
    'gallstones',
    'hepatitis',
    'cirrhosis',
    'autoimmune',
    'allergy',
    'reflux',
    'gastritis',
    'colitis',
    'diverticulitis'
]

def term_score(row):
    text = (
        str(row['extracted_keywords']).lower() + ' ' +
        str(row['patient_summary']).lower()
    )
    high = sum(1 for t in high_risk_terms if t in text)
    medium = sum(1 for t in medium_risk_terms if t in text)
    return high, medium

df[['high_term_score', 'medium_term_score']] = df.apply(
    lambda row: pd.Series(term_score(row)), axis=1
)
print("Signal 1 done ✅")

specialty_risk_map = {

    # HIGH RISK (3)
    'Cardiovascular / Pulmonary': 3,
    'Neurology': 3,
    'Neurosurgery': 3,
    'Oncology': 3,
    'Hematology - Oncology': 3,
    'Emergency Room Reports': 3,
    'Intensive Care Unit (ICU)': 3,
    'Nephrology': 3,
    'Pulmonology': 3,
    'Infectious Disease': 3,
    'Transplant': 3,
    'Critical Care': 3,

    # MEDIUM RISK (2)
    'Gastroenterology': 2,
    'Orthopedic': 2,
    'Endocrinology': 2,
    'Urology': 2,
    'Obstetrics / Gynecology': 2,
    'Rheumatology': 2,
    'General Medicine': 2,
    'Internal Medicine': 2,
    'Family Practice': 2,
    'Surgery': 2,
    'General Surgery': 2,
    'Pain Management': 2,
    'Physical Medicine - Rehab': 2,
    'Psychiatry / Psychology': 2,
    'Sleep Medicine': 2,
    'Pediatrics': 2,
    'Radiology': 2,

    # LOW RISK (1)
    'Dentistry': 1,
    'Dermatology': 1,
    'Ophthalmology': 1,
    'Podiatry': 1,
    'Allergy / Immunology': 1,
    'Cosmetic / Plastic Surgery': 1,
    'Speech Language': 1,
    'Chiropractic': 1,
    'Occupational Medicine': 1,
    'Office Notes': 1,
    'Consult - History and Phy.': 1,
    'Discharge Summary': 1,
    'Letters': 1
}
df['specialty_score'] = df['medical_specialty'].str.strip().map(
    specialty_risk_map
).fillna(2)  # unknown specialties default to medium

print("Signal 2 done ✅")
print(df['specialty_score'].value_counts())

def complexity_score(text):
    text = str(text)
    length = len(text)
    # Normalize to 1-3 scale
    if length > 5000:
        return 3
    elif length > 2000:
        return 2
    else:
        return 1

df['complexity_score'] = df['transcription'].apply(complexity_score)
print("Signal 3 done ✅")

import spacy

nlp = spacy.load("en_core_web_sm")

def negation_penalty(text):
    """
    Detects negated risk terms and reduces score.
    e.g. 'no cancer' should NOT be high risk
    """
    text = str(text)[:500]  # limit for speed
    doc = nlp(text)

    negated_terms = 0
    for token in doc:
        if token.dep_ == 'neg':
            # Check if any high risk term is in same sentence
            sent_text = token.sent.text.lower()
            if any(t in sent_text for t in high_risk_terms):
                negated_terms += 1
    return negated_terms

df['negation_count'] = df['patient_summary'].fillna('').apply(negation_penalty)
print("Signal 4 done ✅")

def compute_final_risk(row):
    # Weighted risk score
    score = (
        row['high_term_score'] * 4 +
        row['medium_term_score'] * 2 +
        row['specialty_score'] * 3 +
        row['complexity_score'] * 1 +
        row['negation_count'] * 2
    )

    if score >= 20:
        return 'High'
    elif score >= 10:
        return 'Medium'
    else:
        return 'Low'

df['risk_label'] = df.apply(compute_final_risk, axis=1)

print("=== Risk Label Distribution ===")
print(df['risk_label'].value_counts())
print(f"\nPercentage:")
print((df['risk_label'].value_counts(normalize=True) * 100).round(1))

import matplotlib.pyplot as plt

colors = {'High': 'red', 'Medium': 'orange', 'Low': 'green'}
counts = df['risk_label'].value_counts()

plt.figure(figsize=(8, 4))
counts.plot(
    kind='bar',
    color=[colors[c] for c in counts.index]
)
plt.title('Risk Label Distribution (Multi-Signal)')
plt.xlabel('Risk Level')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

df.to_csv('mtsamples_with_risk.csv', index=False)
print("Saved ✅")
df.head(5)

!pip install xgboost sentence-transformers shap imbalanced-learn -q

import pandas as pd
import numpy as np

df = pd.read_csv('mtsamples_with_risk.csv')
df = df.dropna(subset=['extracted_keywords', 'medical_specialty', 'risk_label'])

print(f"Dataset size: {df.shape}")
print(df['risk_label'].value_counts())

from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Encode keywords semantically
encoder = SentenceTransformer("all-MiniLM-L6-v2")

print("Encoding keywords...")
keyword_embeddings = encoder.encode(
    df['extracted_keywords'].fillna('').tolist(),
    batch_size=64,
    show_progress_bar=True
)

# One-hot encode medical specialty
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
specialty_ohe = ohe.fit_transform(
    df[['medical_specialty']].fillna('Unknown')
)

# Concatenate all features
X = np.hstack([keyword_embeddings, specialty_ohe])

# Encode risk label
risk_encoder = LabelEncoder()
y = risk_encoder.fit_transform(df['risk_label'])

print(f"Feature shape : {X.shape}")
print(f"Classes       : {risk_encoder.classes_}")

from imblearn.over_sampling import SMOTE
from collections import Counter

print(f"Before SMOTE: {Counter(y)}")

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"After SMOTE : {Counter(y_resampled)}")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled,
    test_size=0.2,
    random_state=42,
    stratify=y_resampled
)

print(f"Train size : {X_train.shape[0]}")
print(f"Test size  : {X_test.shape[0]}")

from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=50
)

print("\nTraining complete ✅")

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

y_pred = model.predict(X_test)

print("=== Classification Report ===")
print(classification_report(
    y_test,
    y_pred,
    target_names=risk_encoder.classes_
))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    xticklabels=risk_encoder.classes_,
    yticklabels=risk_encoder.classes_,
    cmap='Blues'
)
plt.title('Confusion Matrix — Risk Prediction')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.show()

import shap

print("Computing SHAP values...")
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test[:100])

shap.summary_plot(
    shap_values,
    X_test[:100],
    class_names=risk_encoder.classes_,
    max_display=15
)

import joblib

joblib.dump(model, 'risk_model.pkl')
joblib.dump(risk_encoder, 'risk_encoder.pkl')
joblib.dump(ohe, 'ohe_encoder.pkl')
joblib.dump(encoder, 'sentence_encoder.pkl')

# df.to_csv('mtsamples_final.csv', index=False)
print("All models saved ✅")